Nonlinear sdi
ucgmsim/IM_calculation pull request #152
Opened 2022-07-26 23:22 UTC by sungeunbae

On request from @Vahid-Loghman  and @lee-robin .

rotd_values are now obtained by rotating first, then Burks_Baker_2013. Previously it computed the displacements from Burks_Baker_2013 first, then rotated them. 

@Vahid-Loghman verified the output from this code.

2022-07-26 23:29 UTC, jasonmotha submitted a review, later dismissed

2022-07-26 23:45 UTC, jpa198 requested changes
Just need to drop sd_rotd_list then good to go

2022-07-26 23:45 UTC, jpa198 commented on IM_calculation/IM/intensity_measures.py
> -def get_SDI_nd(acceleration, period, NT, DT, z, alpha, dy, dt):
Good catch

2022-07-26 23:45 UTC, jpa198 commented on IM_calculation/Advanced_IM/Models/Burks_Baker_2013/run.py
> +                    func = lambda x: np.max(np.abs(intensity_measures.get_SDI_nd(x, period, DT, z, alpha, dy, dt) * 100), axis=1)
Nice

2022-07-26 23:45 UTC, jpa198 commented on IM_calculation/Advanced_IM/Models/Burks_Baker_2013/run.py
> +    sd_rotd_list = []
Not needed with the lambda

2022-07-26 23:45 UTC, jpa198 commented on IM_calculation/Advanced_IM/Models/Burks_Baker_2013/run.py
>                  for dy in dy_list:
TODO: replace the quad for loop with itertools.product (Would reduce the indentation by 3 levels)
Not needed for this PR, could add in the TODO comment though

2022-07-27 00:00 UTC, jpa198 commented on IM_calculation/Advanced_IM/Models/Burks_Baker_2013/run.py
> +g = 9.81
Does this get used?

2022-07-27 00:51 UTC, jasonmotha approved these changes
Good catch. I remember seeing it added but couldn't remember where it ended up.

2022-07-27 01:01 UTC, jpa198 approved these changes

2022-07-27 01:10 UTC, merged