Adding rrup_points
ucgmsim/IM_calculation pull request #168
Opened 2024-06-06 02:27 UTC by joelridden

Old code used to return the lon, lat and depth points of the rrup values on the srf.
Due to backwards compatibility added a flag to return this option if requested.
(Is required for the NZGMDB, and rather not have a copy of the code just to get the extra points)

2024-06-06 21:17 UTC, lispandfound requested changes

2024-06-06 21:17 UTC, lispandfound commented on IM_calculation/source_site_dist/src_site_dist.py
> +    return_rrup_points=False,
`return_rrup_points` needs a type signature.

2024-06-06 22:36 UTC, sungeunbae submitted a review, later dismissed
Nice work

2024-06-11 00:03 UTC, AndrewRidden-Harper submitted a review, later dismissed
looks good

2024-06-16 20:26 UTC, claudio525 approved these changes

2024-06-16 21:04 UTC, lispandfound approved these changes

2024-06-16 21:45 UTC, AndrewRidden-Harper approved these changes

2024-06-17 00:31 UTC, sungeunbae approved these changes

2024-06-17 00:38 UTC, merged