Update intensity_measures.py
ucgmsim/IM_calculation pull request #78
Opened 2020-10-07 22:32 UTC by jpa198

Break the dot product down to reduce the RAM spike it was causing, allowing multiple threads to run at once.
Pending testing

2020-10-08 21:41 UTC, jasonmotha requested changes

2020-10-08 21:41 UTC, jasonmotha commented on IM_calculation/IM/intensity_measures.py
> +    rotds = []
Create zeros and edit line by line rather than using python lists as a placeholder.

Otherwise looks good.

2020-10-14 21:29 UTC, jpa198 commented
Hossack took 2hrs 23mins to run with extended period standard IMs + rotd50, 100, 100/50

2020-10-14 22:57 UTC, jpa198 commented
Untested, don't commit yet

2020-10-16 01:13 UTC, jpa198 commented
Can be merged, test worked successfully

2020-10-16 01:39 UTC, jpa198 commented
@jasonmotha

2020-10-16 01:45 UTC, jasonmotha approved these changes

2020-10-16 01:47 UTC, merged